easy_admin:
    site_name: '3Tek-Europe Admin'
    
    design:
        assets:
            css:
                - '/admin/custom.css'
            js:
                - '/admin/custom.js'
    
    formats:
        date: 'd/m/Y'
        time: 'H:i'
        datetime: 'd/m/Y H:i:s'
