vich_uploader:
    db_driver: orm

    mappings:
        lot:
            uri_prefix: /uploads/images/
            upload_destination: "%kernel.project_dir%/public/uploads/images/"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
